name: Java CI

on:
  push: # Trigger on every branch push
  pull_request: # Trigger on all pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu' # Options: temurin, zulu, adopt, etc.
          cache: 'maven' # Or 'gradle' if you're using Gradle

      # Install dependencies and run tests (for Maven)
      - name: Build and test with Maven
        run: mvn clean install test